# this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

title: "koddo on code"
description: > # this means to ignore newlines
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://koddo.github.io" # the base hostname & protocol for your site

# email: your-email@domain.com
twitter_username: introstatic
github_username:  koddo
stackoverflow_id:  159149
stackoverflow_username:  koddo

page_source_prefix: "https://github.com/koddo/koddo.github.io/blob/jekyll-source"       # without trailing slash

# Build settings
markdown: kramdown
kramdown:
  input:          GFM
  hard_wrap:      true
  highlighter:    rouge

plugins:
  - jekyll-feed
  # - jekyll-relative-links     # doesn't work for me
# later https://github.com/paulrobertlloyd/jekyll-figure
  
destination: _site
keep_files:
    - .git
exclude:
    - jekyll-serve.sh
    - jekyll-livereload.sh
    - jekyll-publish.sh
    - jekyll-run.sh
    - README.md
    - README-master-branch.md
    - Dockerfile
    - Guardfile
    - TAGS
    - _drafts.txt

  
tag_page_layout: tag_page
tag_page_dir: tag
tag_feed_layout: tag_feed
tag_feed_dir: tag
# tag_permalink_style: pretty
# ignored_tags: [tags,to,ignore]


# timezone: 'Europe/Moscow'


permalink: /blog/:title

collections:
  notes:
    output: true
    title: "Notes"

    
