# this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

title: "koddo on code"
description: > # this means to ignore newlines
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://koddo.github.io" # the base hostname & protocol for your site

# email: your-email@domain.com
twitter_username: introstatic
github_username:  koddo

# Build settings
markdown: kramdown
kramdown:
  input:          GFM
  hard_wrap:      true
  highlighter:    rouge
  
destination: _site
keep_files:
    - _site/.git
exclude:
    - jekyll-serve.sh
    - jekyll-livereload.sh
    - publish.sh
    - gh-pages.sh
    - README.md
    - README-master-branch.md
    - Dockerfile
    - Guardfile
    - _config_livereload.yml
    - notebooks

tag_page_layout: tag_page
tag_page_dir: tag
tag_feed_layout: tag_feed
tag_feed_dir: tag
# tag_permalink_style: pretty
# ignored_tags: [tags,to,ignore]


# timezone: 'Europe/Moscow'


permalink: /blog/:title

# assuming the default is permalink: /:collection/:path
collections:
  ryctoic:
    output: true
    title: "Ryctoic"

    
